### ISSUE TITLE
Insufficient install instructions/install doesn't work

### ISSUE THREAD

**Issue by intuser** [Socrats/EGTTools#1]
Whether I try to install the package in my home directory or in its own environment, using the zip file directly or the setup.py always only egttools-0.1.0.dist-info is installed. Can you please explain the installation a bit better?

**Comment by Socrats** [comment]
Hi intuser. In the version available in master installing is still not implemented. Instead, you should place this repository in a folder of your choice, and add the path to that folder to you PYTHONPATH. I will add more instructions ASAP.

Also, if you would like to try the new version which contains the installing feature as well as the numerical modules with Monte Carlo Simulations implemented in C++, you can pull the files from the feature_mc_simulations branch. The reason why this branch has not been merged to master and made it into a new release is because I am still adding more tests and improving the documentation.

Let me know if it works and whether there is anything else I can do to help.
